---

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: 2021
  sourceType: module
rules:
  no-console: off
  import/extensions: off
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
